skip_commits:
  message: /update readme.*/

os: Visual Studio 2017

install:
  - ps: . ./build/prerequisites.ps1

build: false

build_script:
  - ps: . ./build/build.ps1

deploy_script:
  - ps: . ./build/deploy.ps1

environment:
  PSGallery_Api_Key:
    secure: nn8JeNtzB+nSBOAPnBZTwh9jK+Gtis1XkWl4fTNfp4YB4gb0QrH6qgeLUxeaO9D9
